[package]
name = "smtp2tg"
version = "0.6.7"
authors = [ "arcade@b1t.name" ]
edition = "2024"
license = "0BSD"
repository = "http://fs.b1t.name/smtp2tg"

[dependencies]
async-compat = "0.2.5"
config = { version = "0.15", default-features = false, features = [ "toml" ] }
hostname = "0.4.1"
html-escape = "0.2.13"
clap = { version = "4.6", features = [ "derive" ] }
mail-parser = { version = "0.11", features = ["serde"] }
mailin-embedded = "0.8"
regex = "1.11.1"
smol = "2.0.2"
stacked_errors = "0.7.1"
tgbot = "0.46"

[profile.release]
lto = true
codegen-units = 1

# All tests are moved to tests/
[lib]
test = false

[[bin]]
test = false
name = "smtp2tg"
